/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package enums;

/**
 *
 * @author Uros
 */
public enum Operation {
    LOG_IN, GET_ALL_REPORTS, DELETE_REPORT, INSERT_REPORT, UPDATE_REPORT, SEARCH_REPORTS, GET_ALL_COUNTRIES, INSERT_COUNTRY, UPDATE_COUNTRY, SEARCH_COUNTRIES, GET_ALL_EXAM_PERIODS, DELETE_EXAM_PERIOD, INSERT_EXAM_PERIOD, UPDATE_EXAM_PERIOD, SEARCH_EXAM_PERIODS, GET_ALL_TEACHERS, DELETE_TEACHER, INSERT_TEACHER, UPDATE_TEACHER, SEARCH_TEACHERS, GET_ALL_STUDY_LEVELS, INSERT_STUDY_LEVEL, UPDATE_STUDY_LEVEL, SEARCH_STUDY_LEVEL, GET_ALL_CITIES, GET_ALL_STUDY_PROGRAMS, GET_ALL_MODULES
}
