/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package enums;

/**
 *
 * @author Uros
 */
public enum Operation {
    LOG_IN, GET_ALL_REPORTS, DELETE_REPORT, INSERT_REPORT, UPDATE_REPORT, SEARCH_REPORTS, GET_ALL_COUNTRIES, INSERT_COUNTRY, UPDATE_COUNTRY, SEARCH_COUNTRIES, GET_ALL_EXAM_PERIODS, DELETE_EXAM_PERIOD, INSERT_EXAM_PERIOD, UPDATE_EXAM_PERIOD, SEARCH_EXAM_PERIODS, GET_ALL_TEACHERS, DELETE_TEACHER, INSERT_TEACHER, UPDATE_TEACHER, SEARCH_TEACHERS, GET_ALL_STUDY_LEVELS, INSERT_STUDY_LEVEL, UPDATE_STUDY_LEVEL, SEARCH_STUDY_LEVEL, GET_CITIES, GET_STUDY_PROGRAMS, GET_MODULES, GET_ALL_STUDENTS, GET_ALL_CITIES, GET_ALL_STUDY_PROGRAMS, GET_ALL_MODULES, SEARCH_STUDENTS, INSERT_STUDENT, UPDATE_STUDENT, GET_ALL_COMPANIES, GET_ALL_INTERNSHIPS, DELETE_INTERNSHIP, INSERT_INTERNSHIP, UPDATE_INTERNSHIP, INSERT_REGISTRATION_REQUEST, DELETE_REGISTRATION_REQUEST, INSERT_STUDENT_OFFICER, GET_ALL_REGISTRATION_REQUESTS, GET_ALL_STUDENT_OFFICERS, INSERT_COMPANY, UPDATE_COMPANY,
}
